# Como iremos passar o secret por referência na especificação do Pod, então as keys devem corresponder as variáveis esperadas pela aplicação;
#
# Comando utilizado para gerar esse manifesto já com o conteúdo codificado em base64:
# kubectl create secret generic postgres --from-literal=POSTGRES_USER=mgstec --from-literal=POSTGRES_DB=mgstec --from-literal=POSTGRES_PASSWORD=passw0rd*2024 --dry-run=client -o yaml

apiVersion: v1
type: Opaque
data:
  POSTGRES_DB: bWdzdGVj
  POSTGRES_PASSWORD: cGFzc3cwcmQqMjAyNA==
  POSTGRES_USER: bWdzdGVj
kind: Secret
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: dbnews